KRSolutions\Bundle\KRCMSBundle\Entity\Category:
    type: entity
    repositoryClass: KRSolutions\Bundle\KRCMSBundle\Repository\CategoryRepository
    table: krcms_categories
    indexes:
        name:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        description:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
