KRSolutions\Bundle\KRCMSBundle\Entity\File:
    type: entity
    repositoryClass: KRSolutions\Bundle\KRCMSBundle\Repository\FileRepository
    table: krcms_files
    indexes:
        created_by:
            columns:
                - created_by
        updated_by:
            columns:
                - updated_by
        page_id:
            columns:
                - page_id
    id:
        id:
            type: integer
            nullable: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        createdAt:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: updated_at
        uri:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        title:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        orderId:
            type: integer
            nullable: false
            comment: ''
            default: '0'
            column: order_id
    manyToOne:
        createdBy:
            targetEntity: KRSolutions\Bundle\KRUserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: KRSolutions\Bundle\KRUserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
        page:
            targetEntity: Page
            cascade: {  }
            mappedBy: null
            inversedBy: files
            joinColumns:
                page_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
