KRSolutions\Bundle\KRCMSBundle\Entity\File:
    type: entity
    repositoryClass: KRSolutions\Bundle\KRCMSBundle\Repository\FileRepository
    table: krcms_files
    indexes:
        page_id:
            columns:
                - page_id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: true
            length: 255
        createdAt:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            default: '0000-00-00 00:00:00'
            column: updated_at
        uri:
            type: string
            nullable: false
            length: 255
        title:
            type: string
            nullable: true
            length: 255
        description:
            type: text
            nullable: true
            length: null
        orderId:
            type: integer
            nullable: false
            default: '0'
    manyToOne:
        page:
            targetEntity: PageInterface
            cascade: {  }
            mappedBy: null
            inversedBy: files
            joinColumns:
                page_id:
                    referencedColumnName: id
                    onDelete: "SET NULL"
            orphanRemoval: false
    lifecycleCallbacks: {  }
