KRSolutions\Bundle\KRCMSBundle\Entity\Menu:
    type: entity
    repositoryClass: KRSolutions\Bundle\KRCMSBundle\Repository\MenuRepository
    table: krcms_menus
    indexes:
        name:
            columns:
                - name
    uniqueConstraints:
        name:
            columns:
                - name
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false
            length: 255
        description:
            type: text
            nullable: true
            length: null
    oneToMany:
        pages:
            targetEntity: PageInterface
            mappedBy: menu
            orderBy:
                orderId: asc
    lifecycleCallbacks: {  }
