KRSolutions\Bundle\KRCMSBundle\Entity\PageMeta:
    type: entity
    repositoryClass: KRSolutions\Bundle\KRCMSBundle\Repository\PageMetaRepository
    table: krcms_page_metas
    uniqueConstraints:
        page_meta_key:
            columns:
                - page_id
                - meta_key
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        metaKey:
            type: string
            nullable: false
            length: 255
            column: meta_key
        metaValue:
            type: text
            nullable: true
            length: null
            column: meta_value
    manyToOne:
        page:
            targetEntity: PageInterface
            cascade: {  }
            mappedBy: null
            inversedBy: pageMetas
            joinColumns:
                page_id:
                    referencedColumnName: id
                    onDelete: "CASCADE"
            orphanRemoval: false
    lifecycleCallbacks: {  }
