KRSolutions\Bundle\KRCMSBundle\Entity\PageType:
    type: entity
    repositoryClass: KRSolutions\Bundle\KRCMSBundle\Repository\PageTypeRepository
    table: krcms_page_types
    uniqueConstraints:
        name:
            columns:
                - name
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false
            length: 255
        description:
            type: text
            nullable: true
            length: null
        controller:
            type: string
            nullable: true
            length: 255
        template:
            type: string
            nullable: true
            length: 255
        adminForm:
            type: string
            nullable: true
            length: 255
            column: admin_form
        adminTemplate:
            type: string
            nullable: true
            length: 255
            column: admin_template
        adminFormHandler:
            type: string
            nullable: true
            length: 255
            column: admin_form_handler
        isChild:
            type: boolean
            nullable: false
            default: '0'
            column: is_child
        isMenuItem:
            type: boolean
            nullable: false
            default: '0'
            column: is_menu_item
        hasChildren:
            type: boolean
            nullable: false
            default: '0'
            column: has_children
        childrenOrderBy:
            type: string
            length: 25
            nullable: true
            column: children_order_by
        childrenOrderDirection:
            type: string
            length: 4
            nullable: true
            column: children_order_direction
        childrenPerPage:
            type: integer
            nullable: false
            default: '10'
            column: children_per_page
        hasCategory:
            type: boolean
            nullable: false
            default: '0'
            column: has_category
        hasFiles:
            type: boolean
            nullable: false
            default: '0'
            column: has_files
        hasHeader:
            type: boolean
            nullable: false
            default: '0'
            column: has_header
        hasSlider:
            type: boolean
            nullable: false
            default: '0'
            column: has_slider
        hasContent:
            type: boolean
            nullable: false
            default: '1'
            column: has_content
        maximumToCreate:
            type: integer
            nullable: true
            default: null
            column: maximum_to_create
        roles:
            type: array
            nullable: true
    manyToMany:
        pageTypeParents:
            targetEntity: PageTypeInterface
            mappedBy: pageTypeChildren
        pageTypeChildren:
            targetEntity: PageTypeInterface
            cascade: {  }
            mappedBy: null
            inversedBy: pageTypeParents
            joinTable:
                name: krcms_page_type_children
                joinColumns:
                    -
                        name: parent_page_type_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: child_page_type_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
