KRSolutions\Bundle\KRCMSBundle\Entity\PageType:
    type: entity
    repositoryClass: KRSolutions\Bundle\KRCMSBundle\Repository\PageTypeRepository
    table: krcms_page_types
    uniqueConstraints:
        name:
            columns:
                - name
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false
            length: 255
        description:
            type: text
            nullable: true
            length: null
        pageHandler:
            type: string
            nullable: true
            length: 255
        template:
            type: string
            nullable: true
            length: 255
        adminForm:
            type: string
            nullable: true
            length: 255
        adminTemplate:
            type: string
            nullable: true
            length: 255
        adminFormHandler:
            type: string
            nullable: true
            length: 255
        isChild:
            type: boolean
            nullable: false
            default: '0'
        hasChildren:
            type: boolean
            nullable: false
            default: '0'
        childrenOrderBy:
            type: string
            length: 25
            nullable: true
        childrenOrderDirection:
            type: string
            length: 4
            nullable: true
        hasFiles:
            type: boolean
            nullable: false
            default: '0'
        hasContent:
            type: boolean
            nullable: false
            default: '1'
        roles:
            type: array
            nullable: true
    manyToMany:
        pageTypeParents:
            targetEntity: PageTypeInterface
            mappedBy: pageTypeChildren
        pageTypeChildren:
            targetEntity: PageTypeInterface
            cascade: {  }
            mappedBy: null
            inversedBy: pageTypeParents
            joinTable:
                name: krcms_page_type_children
                joinColumns:
                    -
                        name: parent_page_type_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: child_page_type_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
