KRSolutions\Bundle\KRCMSBundle\Entity\Page:
    type: entity
    repositoryClass: KRSolutions\Bundle\KRCMSBundle\Repository\PageRepository
    table: krcms_pages
    indexes:
        order_id:
            columns:
                - order_id
        page_type_id:
            columns:
                - page_type_id
        permalink:
            columns:
                - permalink
        parent_id:
            columns:
                - parent_id
        created_by:
            columns:
                - created_by
        updated_by:
            columns:
                - updated_by
        menu_id:
            columns:
                - menu_id
        site_id:
            columns:
                - site_id
    uniqueConstraints:
        permalink_and_site_id:
            columns:
                - site_id
                - permalink
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        orderId:
            type: integer
            nullable: false
            comment: ''
            default: '0'
            column: order_id
        createdAt:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            default: '0000-00-00 00:00:00'
            column: updated_at
        publishAt:
            type: datetime
            nullable: true
            column: publish_at
        publishTill:
            type: datetime
            nullable: true
            comment: ''
            column: publish_till
        permalink:
            type: string
            nullable: true
            length: 255
        menuTitle:
            type: string
            nullable: true
            length: 255
            column: menu_title
        title:
            type: string
            nullable: false
            length: 255
        content:
            type: text
            nullable: true
            length: null
        metaKeywords:
            type: string
            nullable: true
            length: 255
            column: meta_keywords
        metaDescription:
            type: string
            nullable: true
            length: 255
            column: meta_description
    manyToOne:
        pageType:
            targetEntity: PageTypeInterface
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                page_type_id:
                    referencedColumnName: id
            orphanRemoval: false
        menu:
            targetEntity: MenuInterface
            cascade: {  }
            mappedBy: null
            inversedBy: pages
            joinColumns:
                menu_id:
                    referencedColumnName: id
            orphanRemoval: false
        site:
            targetEntity: SiteInterface
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                site_id:
                    referencedColumnName: id
            orphanRemoval: false
        parent:
            targetEntity: PageInterface
            cascade: {  }
            mappedBy: null
            inversedBy: pages
            joinColumns:
                parent_id:
                    referencedColumnName: id
                    onDelete: "SET NULL"
            orphanRemoval: false
        createdBy:
            targetEntity: UserInterface
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: UserInterface
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updated_by:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        categories:
            targetEntity: CategoryInterface
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinTable:
                name: krcms_pages_categories
                joinColumns:
                    -
                        name: page_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: category_id
                        referencedColumnName: id
            orderBy: null
        tags:
            targetEntity: TagInterface
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinTable:
                name: krcms_pages_tags
                joinColumns:
                    -
                        name: page_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: tag_id
                        referencedColumnName: id
            orderBy: null
    oneToMany:
        pages:
            targetEntity: PageInterface
            mappedBy: parent
            orderBy:
                orderId: asc
        files:
            targetEntity: FileInterface
            mappedBy: page
            cascade: ["all"]
            orderBy:
                orderId: asc
        pageMetas:
            targetEntity: PageMetaInterface
            mappedBy: page
            cascade: ["all"]
    lifecycleCallbacks: {  }
