KRSolutions\Bundle\KRCMSBundle\Entity\Site:
    type: entity
    repositoryClass: KRSolutions\Bundle\KRCMSBundle\Repository\SiteRepository
    table: krcms_sites
    indexes:
        homepage_id:
            columns:
                - homepage_id
    uniqueConstraints:
        permalink:
            columns:
                - permalink
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        permalink:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        title:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        isActive:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
            column: is_active
    manyToOne:
        homepage:
            targetEntity: PageInterface
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                homepage_id:
                    referencedColumnName: id
                    onDelete: "SET NULL"
            orphanRemoval: false
    manyToMany:
        users:
            targetEntity: UserInterface
            joinTable:
                name: krcms_sites_users
                joinColumns:
                    user_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"
                inverseJoinColumns:
                    group_id:
                       referencedColumnName: id
                       onDelete: "CASCADE"
    lifecycleCallbacks: {  }
