KRSolutions\Bundle\KRCMSBundle\Entity\SliderImage:
    type: entity
    table: krcms_slider_images
    repositoryClass: KRSolutions\Bundle\KRCMSBundle\Repository\SliderImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        uri:
            type: string
            length: 255
        title:
            type: string
            length: 255
            nullable: true
        subtitle:
            type: string
            length: 255
            nullable: true
        linkType:
            type: smallint
        linkHref:
            type: string
            length: 255
            nullable: true
        linkTarget:
            type: string
            length: 255
        linkLabel:
            type: string
            length: 255
            nullable: true
        linkTitle:
            type: string
            length: 255
            nullable: true
        linkClass:
            type: string
            length: 255
            nullable: true
        linkId:
            type: string
            length: 255
            nullable: true
        orderId:
            type: integer
            nullable: false
            default: '0'
            column: order_id
    manyToOne:
        linkPage:
            targetEntity: PageInterface
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                link_page_id:
                    referencedColumnName: id
                    onDelete: "SET NULL"
            orphanRemoval: false
        slider:
            targetEntity: SliderInterface
            cascade: {  }
            mappedBy: null
            inversedBy: sliderImages
            joinColumns:
                slider_id:
                    referencedColumnName: id
                    onDelete: "CASCADE"
            orphanRemoval: false
    lifecycleCallbacks: {  }
