KRSolutions\Bundle\KRCMSBundle\Entity\Tag:
    type: entity
    repositoryClass: KRSolutions\Bundle\KRCMSBundle\Repository\TagRepository
    table: krcms_tags
    indexes:
        name:
            columns:
                - name
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false
            length: 255
    lifecycleCallbacks: {  }
