KRSolutions\Bundle\KRCMSBundle\Entity\User:
    type: mappedSuperclass
    table: krcms_users
    id:
        id:
            type: integer
            nullable: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
