KRSolutions\Bundle\KRCMSBundle\Entity\UserData:
    type: entity
    table: krcms_user_data
    indexes:
        last_selected_site_id:
            columns:
                - last_selected_site_id
    uniqueConstraints:
        user:
            columns:
                - user_id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        user:
            targetEntity: UserInterface
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
                    nullable: false
                    onDelete: "CASCADE"
            orphanRemoval: false
        lastSelectedSite:
            targetEntity: SiteInterface
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                last_selected_site_id:
                    referencedColumnName: id
                    nullable: true
                    onDelete: "SET NULL"
            orphanRemoval: false
    lifecycleCallbacks: {  }
