kr_solutions_krcms_categories_index:
    path: /
    defaults: { _controller: KRSolutionsKRCMSBundle:Category:index }

kr_solutions_krcms_categories_remove:
    path: /remove
    defaults: { _controller: KRSolutionsKRCMSBundle:Category:remove }

kr_solutions_krcms_categories_edit:
    path: /edit/{categoryId}
    defaults: { _controller: KRSolutionsKRCMSBundle:Category:edit }
    requirements:
        categoryId: \d+