kr_solutions_krcms_homepage:
    path:  /
    defaults: { _controller: KRSolutionsKRCMSBundle:Default:page }

kr_solutions_krcms_sitemap:
    path:  /sitemap.xml
    defaults: { _controller: KRSolutionsKRCMSBundle:Default:sitemap }

kr_solutions_krcms_page:
    path:  /{permalink}
    defaults: { _controller: KRSolutionsKRCMSBundle:Default:page, permalink: '' }

kr_solutions_krcms_blog:
    path:  /{permalink}/{pageNumber}
    defaults: { _controller: KRSolutionsKRCMSBundle:Default:page }
    requirements:
        pageNumber: \d+