kr_solutions_krcms_dashboard:
    pattern: /
    defaults: { _controller: KRSolutionsKRCMSBundle:Dashboard:index, siteId: null }

kr_solutions_krcms_dashboard_site:
    pattern: /{siteId}
    defaults: { _controller: KRSolutionsKRCMSBundle:Dashboard:index }
    requirements:
        siteId: \d+

kr_solutions_krcms_helpdesk:
    pattern: /helpdesk
    defaults: { _controller: KRSolutionsKRCMSBundle:Helpdesk:helpdesk }

# Pages
kr_solutions_krcms_pages:
    resource: "@KRSolutionsKRCMSBundle/Resources/config/routing_pages.yml"
    prefix: /pages

# PageTypes
kr_solutions_krcms_page_types:
    resource: "@KRSolutionsKRCMSBundle/Resources/config/routing_page_types.yml"
    prefix: /page-types

# Files
kr_solutions_krcms_files:
    resource: "@KRSolutionsKRCMSBundle/Resources/config/routing_files.yml"
    prefix: /files

# Menus
kr_solutions_krcms_menus:
    resource: "@KRSolutionsKRCMSBundle/Resources/config/routing_menus.yml"
    prefix: /menus

# Categories
kr_solutions_krcms_categories:
    resource: "@KRSolutionsKRCMSBundle/Resources/config/routing_categories.yml"
    prefix: /categories

# Sites
kr_solutions_krcms_sites:
    resource: "@KRSolutionsKRCMSBundle/Resources/config/routing_sites.yml"
    prefix: /sites