kr_solutions_krcms_pages_index:
    path: /{parentPageId}
    defaults: { _controller: KRSolutionsKRCMSBundle:Page:index, parentPageId: null }
    requirements:
        parentPageId: \d+

kr_solutions_krcms_pages_add:
    path: /add/{pageTypeId}
    defaults: { _controller: KRSolutionsKRCMSBundle:Page:edit }
    requirements:
        pageTypeId: \d+

kr_solutions_krcms_pages_edit:
    path: /edit/{pageId}
    defaults: { _controller: KRSolutionsKRCMSBundle:Page:edit }
    requirements:
        pageId: \d+

kr_solutions_krcms_pages_remove:
    path: /remove/{pageId}
    defaults: { _controller: KRSolutionsKRCMSBundle:Page:remove }
    requirements:
        pageId: \d+

kr_solutions_krcms_pages_generate_permalink:
    path: /generate-permalink
    defaults: { _controller: KRSolutionsKRCMSBundle:Page:generatePermalink }

kr_solutions_krcms_pages_change_order:
    path: /change-pages-order
    defaults: { _controller: KRSolutionsKRCMSBundle:Page:changeOrder }