kr_solutions_krcms_sites_index:
    path: /
    defaults: { _controller: KRSolutionsKRCMSBundle:Site:index }

kr_solutions_krcms_sites_remove:
    path: /remove/{siteId}
    defaults: { _controller: KRSolutionsKRCMSBundle:Site:remove }
    requirements:
        siteId: \d+

kr_solutions_krcms_sites_edit:
    path: /edit/{siteId}
    defaults: { _controller: KRSolutionsKRCMSBundle:Site:edit }
    requirements:
        siteId: \d+

kr_solutions_krcms_sites_add:
    path: /add
    defaults: { _controller: KRSolutionsKRCMSBundle:Site:edit }