kr_solutions_krcms_categories_index:
    path: /
    defaults: { _controller: KRSolutionsKRCMSBundle:Categories:index }

kr_solutions_krcms_category_remove:
    path: /remove/{categoryId}
    defaults: { _controller: KRSolutionsKRCMSBundle:Category:remove }
    requirements:
        categoryId: \d+

kr_solutions_krcms_category_edit:
    path: /edit/{categoryId}
    defaults: { _controller: KRSolutionsKRCMSBundle:Category:edit }
    requirements:
        categoryId: \d+