kr_solutions_krcms_page_types_index:
    path: /
    defaults: { _controller: KRSolutionsKRCMSBundle:PageType:index }

kr_solutions_krcms_page_types_remove:
    path: /remove/{pageTypeId}
    defaults: { _controller: KRSolutionsKRCMSBundle:PageType:remove }
    requirements:
        pageId: \d+

kr_solutions_krcms_page_types_edit:
    path: /edit/{pageTypeId}
    defaults: { _controller: KRSolutionsKRCMSBundle:PageType:edit }
    requirements:
        pageId: \d+

kr_solutions_krcms_page_types_add:
    path: /add
    defaults: { _controller: KRSolutionsKRCMSBundle:PageType:edit }