kr_solutions_krcms_page_types_index:
    pattern: /
    defaults: { _controller: KRSolutionsKRCMSBundle:PageType:index }

kr_solutions_krcms_page_types_edit:
    pattern: /edit/{pageTypeId}
    defaults: { _controller: KRSolutionsKRCMSBundle:PageType:edit }
    requirements:
        pageId: \d+

kr_solutions_krcms_page_types_remove:
    pattern: /remove/{pageTypeId}
    defaults: { _controller: KRSolutionsKRCMSBundle:PageType:remove }
    requirements:
        pageId: \d+