services:

    kr_solutions_krcms.page_handler.page:
        class: KRSolutions\Bundle\KRCMSBundle\PageHandler\PageHandler
        calls:
            - [setContainer, ["@service_container"]]

    kr_solutions_krcms.menu_twig_extension:
        class: KRSolutions\Bundle\KRCMSBundle\TwigExtension\MenuTwigExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    kr_solutions_krcms.excerpt_twig_extension:
        class: KRSolutions\Bundle\KRCMSBundle\TwigExtension\ExcerptTwigExtension
        tags:
            - { name: twig.extension }

    kr_solutions_krcms.form.type.krcms_category:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\KRCMSCategoryType
        arguments: ["%kr_solutions_krcms.model.category_class%"]
        tags:
            - { name: form.type, alias: krcms_category }

    kr_solutions_krcms.form.type.krcms_file:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\KRCMSFileType
        arguments: ["%kr_solutions_krcms.model.file_class%"]
        tags:
            - { name: form.type, alias: krcms_file }

    kr_solutions_krcms.form.type.krcms_menu:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\KRCMSMenuType
        arguments: ["%kr_solutions_krcms.model.menu_class%"]
        tags:
            - { name: form.type, alias: krcms_menu }

    kr_solutions_krcms.form.type.krcms_page:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\KRCMSPageType
        arguments: ["%kr_solutions_krcms.model.page_class%"]
        tags:
            - { name: form.type, alias: krcms_page }

    kr_solutions_krcms.form.type.krcms_page_type:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\KRCMSPageTypeType
        arguments: ["%kr_solutions_krcms.model.page_type_class%"]
        tags:
            - { name: form.type, alias: krcms_page_type }

    kr_solutions_krcms.form.type.krcms_site:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\KRCMSSiteType
        arguments: ["%kr_solutions_krcms.model.site_class%"]
        tags:
            - { name: form.type, alias: krcms_site }

    kr_solutions_krcms.form.type.krcms_tag:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\KRCMSTagType
        arguments: ["%kr_solutions_krcms.model.tag_class%"]
        tags:
            - { name: form.type, alias: krcms_tag }

    kr_solutions_krcms.site_manager:
        class: KRSolutions\Bundle\KRCMSBundle\Doctrine\SiteManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%kr_solutions_krcms.model.site_class%"

    kr_solutions_krcms.page_manager:
        class: KRSolutions\Bundle\KRCMSBundle\Doctrine\PageManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%kr_solutions_krcms.model.page_class%"

    kr_solutions_krcms.menu_manager:
        class: KRSolutions\Bundle\KRCMSBundle\Doctrine\MenuManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%kr_solutions_krcms.model.menu_class%"

    kr_solutions_krcms.doctrine.orm.listeners.resolve_target_entity:
        class: KRSolutions\Bundle\KRCMSBundle\Doctrine\ORM\Tools\ResolveTargetEntityListener
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }