services:
#    kr_solutions_krcms.example:
#        class: KRSolutions\Bundle\KRCMSBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    kr_solutions_krcms.page_handler.page:
        class: KRSolutions\Bundle\KRCMSBundle\PageHandler\PageHandler
        calls:
            - [setContainer, ["@service_container"]]

    kr_solutions_krcms.menu_twig_extension:
        class: KRSolutions\Bundle\KRCMSBundle\TwigExtension\MenuTwigExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    kr_solutions_krcms.excerpt_twig_extension:
        class: KRSolutions\Bundle\KRCMSBundle\TwigExtension\ExcerptTwigExtension
        tags:
            - { name: twig.extension }

    kr_solutions_krcms.form.type.category:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\CategoryType
        tags:
            - { name: form.type, alias: category }

    kr_solutions_krcms.form.type.krcms_file:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\KRCMSFileType
        tags:
            - { name: form.type, alias: krcms_file }

    kr_solutions_krcms.form.type.menu:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\MenuType
        tags:
            - { name: form.type, alias: menu }

    kr_solutions_krcms.form.type.page:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\PageType
        tags:
            - { name: form.type, alias: page }

    kr_solutions_krcms.form.type.page_type:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\PageTypeType
        tags:
            - { name: form.type, alias: page_type }

    kr_solutions_krcms.form.type.site:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\SiteType
        tags:
            - { name: form.type, alias: site }

    kr_solutions_krcms.form.type.tag:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\TagType
        tags:
            - { name: form.type, alias: tag }