KRSolutions\Bundle\KRCMSBundle\Entity\Page:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - permalink
            message: kr_solutions_krcms.page.permalink.unique
    properties:
        title:
            - NotBlank:
                message: kr_solutions_krcms.page.title.not_blank
            - Length:
                max: 255

KRSolutions\Bundle\KRCMSBundle\Entity\File:
    properties:
        uri:
            - NotBlank:
                message: kr_solutions_krcms.file.uri.not_blank
            - Length:
                max: 255

KRSolutions\Bundle\KRCMSBundle\Entity\PageType:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: name
            message: kr_solutions_krcms.page_type.name.unique
    properties:
        name:
            - NotBlank:
                message: kr_solutions_krcms.page_type.name.not_blank
            - Length:
                max: 255

KRSolutions\Bundle\KRCMSBundle\Entity\Menu:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name]
            message: kr_solutions_krcms.menu.name.unique
    properties:
        name:
            - NotBlank:
                message: kr_solutions_krcms.menu.name.not_blank
            - Length:
                max: 255