KRSolutions\Bundle\KRCMSBundle\Entity\Menu:
#    constraints:
#        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
#            fields: name
#            message: "De naam van het menu moet uniek zijn"

    properties:
        name:
            - NotBlank:
                message: kr_solutions_krcms.menu.name.not_blank
            - Length:
                max: 255

KRSolutions\Bundle\KRCMSBundle\Entity\Page:
    properties:
        title:
            - NotBlank:
                message: kr_solutions_krcms.page.title.not_blank
            - Length:
                max: 255

KRSolutions\Bundle\KRCMSBundle\Entity\File:
    properties:
        uri:
            - NotBlank:
                message: kr_solutions_krcms.file.uri.not_blank
            - Length:
                max: 255

KRSolutions\Bundle\KRCMSBundle\Entity\Site:
    properties:
        title:
            - NotBlank:
                message: kr_solutions_krcms.site.title.not_blank
            - Length:
                max: 255