services:
    kr_solutions_krcms.form.type.krcms_category:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\KRCMSCategoryType
        arguments: ["%kr_solutions_krcms.model.category_class%"]
        tags:
            - { name: form.type, alias: krcms_category }

    kr_solutions_krcms.form.type.krcms_file:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\KRCMSFileType
        arguments: ["%kr_solutions_krcms.model.file_class%"]
        tags:
            - { name: form.type, alias: krcms_file }

    kr_solutions_krcms.form.type.krcms_header:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\KRCMSHeaderType
        arguments: ["%kr_solutions_krcms.model.header_class%"]
        tags:
            - { name: form.type, alias: krcms_header }

    kr_solutions_krcms.form.type.krcms_menu:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\KRCMSMenuType
        arguments: ["%kr_solutions_krcms.model.menu_class%"]
        tags:
            - { name: form.type, alias: krcms_menu }

    kr_solutions_krcms.form.type.krcms_page:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\KRCMSPageType
        arguments: ["%kr_solutions_krcms.model.page_class%"]
        tags:
            - { name: form.type, alias: krcms_page }

    kr_solutions_krcms.form.type.krcms_page_type:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\KRCMSPageTypeType
        arguments: ["%kr_solutions_krcms.model.page_type_class%"]
        tags:
            - { name: form.type, alias: krcms_page_type }

    kr_solutions_krcms.form.type.krcms_slider:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\KRCMSSliderType
        arguments: ["%kr_solutions_krcms.model.slider_class%"]
        tags:
            - { name: form.type, alias: krcms_slider }

    kr_solutions_krcms.form.type.krcms_slider_image:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\KRCMSSliderImageType
        arguments: ["%kr_solutions_krcms.model.slider_image_class%"]
        tags:
            - { name: form.type, alias: krcms_slider_image }

    kr_solutions_krcms.form.type.krcms_tag:
        class: KRSolutions\Bundle\KRCMSBundle\Form\Type\KRCMSTagType
        arguments: ["%kr_solutions_krcms.model.tag_class%"]
        tags:
            - { name: form.type, alias: krcms_tag }