services:
    kr_solutions_krcms.slider_manager:
        class: KRSolutions\Bundle\KRCMSBundle\Doctrine\SliderManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%kr_solutions_krcms.model.slider_class%"

    kr_solutions_krcms.page_manager:
        class: KRSolutions\Bundle\KRCMSBundle\Doctrine\PageManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%kr_solutions_krcms.model.page_class%"

    kr_solutions_krcms.menu_manager:
        class: KRSolutions\Bundle\KRCMSBundle\Doctrine\MenuManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%kr_solutions_krcms.model.menu_class%"