services:
    kr_solutions_krcms.page_handler.page:
        class: KRSolutions\Bundle\KRCMSBundle\PageHandler\PageHandler
        calls:
            - [setContainer, ["@service_container"]]

    kr_solutions_krcms.doctrine.orm.listeners.resolve_target_entity:
        class: KRSolutions\Bundle\KRCMSBundle\Doctrine\ORM\Tools\ResolveTargetEntityListener
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }